/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/issues/new/choose\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ShopShippingProfileUpgradesResultsInner
 */
public class ShopShippingProfileUpgradesResultsInnerTest {
    private final ShopShippingProfileUpgradesResultsInner model = new ShopShippingProfileUpgradesResultsInner();

    /**
     * Model tests for ShopShippingProfileUpgradesResultsInner
     */
    @Test
    public void testShopShippingProfileUpgradesResultsInner() {
        // TODO: test ShopShippingProfileUpgradesResultsInner
    }

    /**
     * Test the property 'shippingProfileId'
     */
    @Test
    public void shippingProfileIdTest() {
        // TODO: test shippingProfileId
    }

    /**
     * Test the property 'upgradeId'
     */
    @Test
    public void upgradeIdTest() {
        // TODO: test upgradeId
    }

    /**
     * Test the property 'upgradeName'
     */
    @Test
    public void upgradeNameTest() {
        // TODO: test upgradeName
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'secondaryPrice'
     */
    @Test
    public void secondaryPriceTest() {
        // TODO: test secondaryPrice
    }

    /**
     * Test the property 'shippingCarrierId'
     */
    @Test
    public void shippingCarrierIdTest() {
        // TODO: test shippingCarrierId
    }

    /**
     * Test the property 'mailClass'
     */
    @Test
    public void mailClassTest() {
        // TODO: test mailClass
    }

    /**
     * Test the property 'minDeliveryDays'
     */
    @Test
    public void minDeliveryDaysTest() {
        // TODO: test minDeliveryDays
    }

    /**
     * Test the property 'maxDeliveryDays'
     */
    @Test
    public void maxDeliveryDaysTest() {
        // TODO: test maxDeliveryDays
    }

}
