/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents a processing profile to set a product offering&#39;s readiness state and processing time info.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-17T14:01:44.125538310+02:00[Europe/Berlin]")
public class ShopProcessingProfile {
  public static final String SERIALIZED_NAME_SHOP_ID = "shop_id";
  @SerializedName(SERIALIZED_NAME_SHOP_ID)
  private Long shopId;

  public static final String SERIALIZED_NAME_READINESS_STATE_ID = "readiness_state_id";
  @SerializedName(SERIALIZED_NAME_READINESS_STATE_ID)
  private Long readinessStateId;

  /**
   * The readiness state of a product: \\\&quot;1\\\&quot; means \\\&quot;ready_to_ship\\\&quot;, and \\\&quot;2\\\&quot; means \\\&quot;made_to_order\\\&quot;
   */
  @JsonAdapter(ReadinessStateEnum.Adapter.class)
  public enum ReadinessStateEnum {
    READY_TO_SHIP("ready_to_ship"),
    
    MADE_TO_ORDER("made_to_order");

    private String value;

    ReadinessStateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ReadinessStateEnum fromValue(String value) {
      for (ReadinessStateEnum b : ReadinessStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ReadinessStateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ReadinessStateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ReadinessStateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ReadinessStateEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_READINESS_STATE = "readiness_state";
  @SerializedName(SERIALIZED_NAME_READINESS_STATE)
  private ReadinessStateEnum readinessState;

  public static final String SERIALIZED_NAME_MIN_PROCESSING_DAYS = "min_processing_days";
  @SerializedName(SERIALIZED_NAME_MIN_PROCESSING_DAYS)
  private Long minProcessingDays;

  public static final String SERIALIZED_NAME_MAX_PROCESSING_DAYS = "max_processing_days";
  @SerializedName(SERIALIZED_NAME_MAX_PROCESSING_DAYS)
  private Long maxProcessingDays;

  public static final String SERIALIZED_NAME_PROCESSING_DAYS_DISPLAY_LABEL = "processing_days_display_label";
  @SerializedName(SERIALIZED_NAME_PROCESSING_DAYS_DISPLAY_LABEL)
  private String processingDaysDisplayLabel;

  public ShopProcessingProfile() {
  }

  public ShopProcessingProfile shopId(Long shopId) {
    
    this.shopId = shopId;
    return this;
  }

   /**
   * The unique positive non-zero numeric ID for an Etsy Shop.
   * minimum: 1
   * @return shopId
  **/
  @javax.annotation.Nullable

  public Long getShopId() {
    return shopId;
  }


  public void setShopId(Long shopId) {
    this.shopId = shopId;
  }


  public ShopProcessingProfile readinessStateId(Long readinessStateId) {
    
    this.readinessStateId = readinessStateId;
    return this;
  }

   /**
   * The numeric ID of the [processing profile](/documentation/reference#operation/getShopReadinessStateDefinition) associated with the listing. Required when listing type is &#x60;physical&#x60;.
   * minimum: 1
   * @return readinessStateId
  **/
  @javax.annotation.Nullable

  public Long getReadinessStateId() {
    return readinessStateId;
  }


  public void setReadinessStateId(Long readinessStateId) {
    this.readinessStateId = readinessStateId;
  }


  public ShopProcessingProfile readinessState(ReadinessStateEnum readinessState) {
    
    this.readinessState = readinessState;
    return this;
  }

   /**
   * The readiness state of a product: \\\&quot;1\\\&quot; means \\\&quot;ready_to_ship\\\&quot;, and \\\&quot;2\\\&quot; means \\\&quot;made_to_order\\\&quot;
   * @return readinessState
  **/
  @javax.annotation.Nullable

  public ReadinessStateEnum getReadinessState() {
    return readinessState;
  }


  public void setReadinessState(ReadinessStateEnum readinessState) {
    this.readinessState = readinessState;
  }


  public ShopProcessingProfile minProcessingDays(Long minProcessingDays) {
    
    this.minProcessingDays = minProcessingDays;
    return this;
  }

   /**
   * The minimum number of days for processing a specific product.
   * minimum: 0
   * @return minProcessingDays
  **/
  @javax.annotation.Nullable

  public Long getMinProcessingDays() {
    return minProcessingDays;
  }


  public void setMinProcessingDays(Long minProcessingDays) {
    this.minProcessingDays = minProcessingDays;
  }


  public ShopProcessingProfile maxProcessingDays(Long maxProcessingDays) {
    
    this.maxProcessingDays = maxProcessingDays;
    return this;
  }

   /**
   * The maximum number of days for processing a specific product.
   * minimum: 0
   * @return maxProcessingDays
  **/
  @javax.annotation.Nullable

  public Long getMaxProcessingDays() {
    return maxProcessingDays;
  }


  public void setMaxProcessingDays(Long maxProcessingDays) {
    this.maxProcessingDays = maxProcessingDays;
  }


  public ShopProcessingProfile processingDaysDisplayLabel(String processingDaysDisplayLabel) {
    
    this.processingDaysDisplayLabel = processingDaysDisplayLabel;
    return this;
  }

   /**
   * Translated display label string for processing days, for example \&quot;3 - 5 days\&quot;.
   * @return processingDaysDisplayLabel
  **/
  @javax.annotation.Nullable

  public String getProcessingDaysDisplayLabel() {
    return processingDaysDisplayLabel;
  }


  public void setProcessingDaysDisplayLabel(String processingDaysDisplayLabel) {
    this.processingDaysDisplayLabel = processingDaysDisplayLabel;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopProcessingProfile shopProcessingProfile = (ShopProcessingProfile) o;
    return Objects.equals(this.shopId, shopProcessingProfile.shopId) &&
        Objects.equals(this.readinessStateId, shopProcessingProfile.readinessStateId) &&
        Objects.equals(this.readinessState, shopProcessingProfile.readinessState) &&
        Objects.equals(this.minProcessingDays, shopProcessingProfile.minProcessingDays) &&
        Objects.equals(this.maxProcessingDays, shopProcessingProfile.maxProcessingDays) &&
        Objects.equals(this.processingDaysDisplayLabel, shopProcessingProfile.processingDaysDisplayLabel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shopId, readinessStateId, readinessState, minProcessingDays, maxProcessingDays, processingDaysDisplayLabel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopProcessingProfile {\n");
    sb.append("    shopId: ").append(toIndentedString(shopId)).append("\n");
    sb.append("    readinessStateId: ").append(toIndentedString(readinessStateId)).append("\n");
    sb.append("    readinessState: ").append(toIndentedString(readinessState)).append("\n");
    sb.append("    minProcessingDays: ").append(toIndentedString(minProcessingDays)).append("\n");
    sb.append("    maxProcessingDays: ").append(toIndentedString(maxProcessingDays)).append("\n");
    sb.append("    processingDaysDisplayLabel: ").append(toIndentedString(processingDaysDisplayLabel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("shop_id");
    openapiFields.add("readiness_state_id");
    openapiFields.add("readiness_state");
    openapiFields.add("min_processing_days");
    openapiFields.add("max_processing_days");
    openapiFields.add("processing_days_display_label");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ShopProcessingProfile
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ShopProcessingProfile.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ShopProcessingProfile is not found in the empty JSON string", ShopProcessingProfile.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ShopProcessingProfile.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ShopProcessingProfile` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("readiness_state") != null && !jsonObj.get("readiness_state").isJsonNull()) && !jsonObj.get("readiness_state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `readiness_state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("readiness_state").toString()));
      }
      if ((jsonObj.get("processing_days_display_label") != null && !jsonObj.get("processing_days_display_label").isJsonNull()) && !jsonObj.get("processing_days_display_label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `processing_days_display_label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("processing_days_display_label").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ShopProcessingProfile.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ShopProcessingProfile' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ShopProcessingProfile> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ShopProcessingProfile.class));

       return (TypeAdapter<T>) new TypeAdapter<ShopProcessingProfile>() {
           @Override
           public void write(JsonWriter out, ShopProcessingProfile value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ShopProcessingProfile read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ShopProcessingProfile given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ShopProcessingProfile
  * @throws IOException if the JSON string is invalid with respect to ShopProcessingProfile
  */
  public static ShopProcessingProfile fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ShopProcessingProfile.class);
  }

 /**
  * Convert an instance of ShopProcessingProfile to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

